# Exercise No.31

# Why is there an error?
def foo(a=1, b=2):
	return a + b


x = foo - 1

# Solution
# Because there is no "()" at the end of foo when assigning it to x


