# Exercise No.32

# What is the following output?
c = 1
def foo():
    return c
c = 3
print(foo())


# Solution
# 3 because calling foo() will return c which is now equal to 3


